"""created columns

Revision ID: 0df43a7bd886
Revises: 
Create Date: 2025-10-29 20:07:56.403903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df43a7bd886'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('storage_files')
    op.drop_table('recovery_codes')
    op.drop_table('one_time_codes')
    op.drop_table('refresh_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('expiresIn', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refreshTokenHash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('lastUsed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_78744bff965517952df6c02da76'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_9190032f6967b7971dca07d69f3')),
    sa.UniqueConstraint('refreshTokenHash', name=op.f('UQ_914c273c797c19ce9a0000a9c51'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('one_time_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('expiresIn', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_ae6fc30aa12eeae02fec8d6b63e')),
    sa.UniqueConstraint('code', name=op.f('UQ_cf0cd69c57dfbf6f96ed6d0be63'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('recovery_codes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recovery_codes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recovery_codes_pkey')),
    sa.UniqueConstraint('code_hash', name=op.f('recovery_codes_code_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('storage_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('storage_files_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('storage_files_pkey')),
    sa.UniqueConstraint('key', name=op.f('storage_files_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_a3ffb1c0c8416b9fc6f907b7433')),
    sa.UniqueConstraint('telegram_id', name=op.f('UQ_1a1e4649fd31ea6ec6b025c7bfc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
